version: '3.4'

volumes:
  data:
    name: licit-data

services:
  styles:
    container_name: styles
    image: melgish/licit-style-service
    restart: unless-stopped
    ports:
       # external port must match proxy.conf.js
      - 3000:3000
    environment:
      - HTTP_PORT=3000
      - LOG_LEVEL=debug
      - DATA_ROOT=/app/data
      - SAVE_SECONDS=30
    volumes:
      - data:/app/data

  content:
    container_name: content
    image: melgish/licit-tiny-cm
    restart: unless-stopped
    ports:
      # external port must match proxy.conf.js
      - 3001:3000
    environment:
      - HTTP_PORT=3000
      - LOG_LEVEL=debug
      - DATA_ROOT=/app/data
      - SAVE_SECONDS=30
    volumes:
      - data:/app/data
